[project]
name = "django-photo-gallery"
version = "1.0"
description = "A photo gallery website built using Django."
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "crispy-bootstrap5==2025.6",
    "django==4.2.17",
    "django-crispy-forms==2.3",
    "django-imagekit==5.0.0",
]
